const OWNER='himumidmohamedi-cmd', REPO='jeff-electronics', BRANCH='main';
const API=`https://api.github.com/repos/${OWNER}/${REPO}/contents/products?ref=${BRANCH}`;
const RAW=`https://raw.githubusercontent.com/${OWNER}/${REPO}/${BRANCH}/products/`;
const grid=document.getElementById('productGrid'), heroGrid=document.getElementById('heroGrid'), status=document.getElementById('status'), search=document.getElementById('search'), chips=document.getElementById('chips'), loadMore=document.getElementById('loadMore'), count=document.getElementById('count');
let all=[], filtered=[], shown=0, category='Zote';
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function nice(name){return name.replace(/\.[^.]+$/,'').replace(/WhatsApp Image/gi,'').replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim()||'JEFF Electronics';}
function cat(name){const n=name.toLowerCase(); if(/phone|iphone|samsung|tecno|infinix|redmi|oppo|vivo|mobile/.test(n))return'Simu'; if(/watch|smartwatch|band/.test(n))return'Smart Watch'; if(/head|ear|airpod|speaker|audio|sound/.test(n))return'Audio'; if(/charg|cable|usb|adapter|power|battery/.test(n))return'Chargers'; if(/case|cover|glass|screen|holder|stand/.test(n))return'Accessories'; return'Electronics';}
function render(){grid.innerHTML='';const q=search.value.toLowerCase().trim();filtered=all.filter(x=>(category==='Zote'||x.category===category)&&(!q||x.name.toLowerCase().includes(q)||x.category.toLowerCase().includes(q)));shown=Math.min(12,filtered.length);draw();status.textContent=filtered.length?`${filtered.length} bidhaa zimepatikana`:'Hakuna bidhaa inayolingana na utafutaji.';loadMore.hidden=shown>=filtered.length;}
function draw(){grid.innerHTML=filtered.slice(0,shown).map(x=>`<article class="product"><img loading="lazy" src="${x.url}" alt="${esc(x.name)}" onerror="this.parentElement.style.display='none'"><div class="product-body"><div class="product-name" title="${esc(x.name)}">${esc(x.name)}</div><div class="product-meta">${esc(x.category)}</div><div class="product-actions"><a class="small-btn" href="${x.url}" target="_blank">Tazama</a><a class="small-btn wa" href="https://wa.me/255768384919?text=${encodeURIComponent('Habari JEFF ELECTRONICS, naulizia '+x.name)}" target="_blank">WhatsApp</a></div></div></article>`).join('');}
function makeChips(){const cats=['Zote',...new Set(all.map(x=>x.category))];chips.innerHTML=cats.map(c=>`<button class="chip ${c==='Zote'?'active':''}" data-cat="${c}">${c}</button>`).join('');chips.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{category=b.dataset.cat;chips.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');render();});}
async function load(){try{const r=await fetch(API,{headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw new Error('API '+r.status);const files=await r.json();all=files.filter(f=>f.type==='file'&&/\.(jpe?g|png|webp|gif)$/i.test(f.name)).map(f=>({name:nice(f.name),category:cat(f.name),url:RAW+encodeURIComponent(f.name).replace(/%2F/g,'/')}));count.textContent=all.length;makeChips();render();const hero=all.slice(0,10);heroGrid.innerHTML=hero.map(x=>`<img src="${x.url}" alt="" loading="lazy">`).join('');if(!all.length)status.textContent='Hakuna picha ndani ya products/.';}catch(e){status.innerHTML='Imeshindikana kusoma bidhaa moja kwa moja. Hakikisha repository ni Public na folder <b>products</b> lipo.';console.error(e)}}
search.addEventListener('input',render);loadMore.onclick=()=>{shown=Math.min(shown+12,filtered.length);draw();loadMore.hidden=shown>=filtered.length};document.getElementById('year').textContent=new Date().getFullYear();document.getElementById('menuBtn').onclick=()=>document.getElementById('nav').classList.toggle('open');
load();
